apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./dev-config/ingress-srv.yaml
      - ./dev-config/auth-depl.yaml
      - ./dev-config/auth-mongo-depl.yaml
      - ./dev-config/products-depl.yaml
      - ./dev-config/products-mongo-depl.yaml
      - ./dev-config/nats-depl.yaml
      - ./dev-config/orders-depl.yaml
      - ./dev-config/orders-mongo-depl.yaml
      - ./dev-config/order-expire-depl.yaml
      - ./dev-config/order-expire-redis-depl.yaml
      - ./dev-config/payments-depl.yaml
      - ./dev-config/payments-mongo-depl.yaml

build:
  local:
    push: false
  artifacts:
    - image: chabunsi/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: chabunsi/products
      context: products
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: chabunsi/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: chabunsi/order-expire
      context: order-expire
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: chabunsi/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    # - image: chabunsi/front
    #   context: front
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
