apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      app: orders
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: "gcr.io/chabunsi-project/orders"
          env:
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_ADMIN_ID
              value: 'kafka-admin'
            - name: BROKER_1
              value: 'kafka-service:9092'
            - name: MONGO_URI
              value: 'mongodb://mongo-srv:27017/orders'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_KEY
          resources:
            requests:
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
    - name: orders
      protocol: TCP
      port: 3000
      targetPort: 3000