apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: "gcr.io/chabunsi-project/products"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 180
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 180
          env:
            - name: MONGO_URI
              value: 'mongodb://mongo:27017/products'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 3000
      targetPort: 3000
